name: uorf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=11.0.221
  - numpy
  - pillow
  - pip=21.0.1
  - pip:
      - dominate==2.6.0
      - imageio==2.9.0
      - lpips==0.1.3
      - tqdm
      - matplotlib==3.3.4
      - piq==0.5.4
      - scikit-image==0.18.1
      - scikit-learn==0.24.2
      - visdom==0.1.8.9
